# Generated by Django 5.1.1 on 2024-09-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('milestone_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('child_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='child.child')),
            ],
        ),
    ]
