# Generated by Django 5.1.1 on 2024-09-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateTimeField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField()),
                ('updates_at', models.DateTimeField()),
                ('parent_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parent.parent')),
            ],
        ),
    ]
